#!/bin/bash
set -x
PID=`ps -ef | grep -i hiveserver2 | grep -v grep |  awk '{ print $2 }'`
if [ "${PID}" != "" ]
then
	echo "+ sudo kill -9 ${PID} ...."
	sudo kill -9 ${PID}
	sleep 2
fi
read dummy
#nohup sudo -b  /usr/lib/hive/bin/hive --config /etc/hive/conf.server --service hiveserver2 > /dev/null 2>&1 &
sudo -b su -l hive -c "nohup /usr/lib/hive/bin/hiveserver2 -hiveconf hive.metastore.uris=\" \" > /var/log/hive/hive-server2.log 2>/var/log/hive/hive-server2.log &"
sleep 5
echo 
echo
ps -ef | grep -i hiveserver2 | grep -v grep 
echo
echo
